version: '3.4'

services:

  web:
    image: jmalloc/echo-server
    container_name: web

  agent:
    image: ${DOCKER_REGISTRY-}agent
    build:
      context: ..
      dockerfile: agent/Dockerfile


  haproxy:
    image: haproxy:lts
    ports:
    - "8000:80"
    container_name: haproxy
    volumes:
    - "./haproxy/:/usr/local/etc/haproxy"
    depends_on:
    - web
    - agent